import type { Operator } from "../types";

export type ProviderParkConfig = {
  provider: "campspot" | "letscamp";
  slug: string;
  name: string;
  region: string;
  vendorUrl: string;
};

export type OperatorConfig = Operator & {
  providerParks?: ProviderParkConfig[];
};

const ONTARIO_PARKS: OperatorConfig = {
  id: "ontario_parks", name: "Ontario Parks", vendor: "camis5",
  base_url: "https://reservations.ontarioparks.ca",
  booking_url: "https://reservations.ontarioparks.ca/create-booking/results",
  active: true,
};

const PARKS_CANADA: OperatorConfig = {
  id: "parks_canada", name: "Parks Canada", vendor: "pcrs",
  base_url: "https://reservation.pc.gc.ca",
  booking_url: "https://reservation.pc.gc.ca/create-booking/results",
  active: true,
};

const ST_LAWRENCE_PARKS: OperatorConfig = {
  id: "st_lawrence_parks", name: "Parks of the St. Lawrence", vendor: "camis5",
  base_url: "https://reservations.parks.on.ca",
  booking_url: "https://reservations.parks.on.ca/create-booking/results",
  active: true,
};

function gtc(id: string, name: string, host: string): OperatorConfig {
  return {
    id: `gtc_${id}`, name, vendor: "goingtocamp",
    base_url: `https://${host}`,
    booking_url: `https://${host}/create-booking/results`,
    active: true,
  };
}

const CAMPSPOT_ONTARIO_PRIVATE_PARKS: ProviderParkConfig[] = [
  {
    provider: "campspot",
    slug: "accommodatingbay",
    name: "Accommodating Bay, Prince Edward County",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/accommodatingbay",
  },
  {
    provider: "campspot",
    slug: "algonquin-pines",
    name: "Algonquin Pines Campground, Dwight",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/algonquin-pines",
  },
  {
    provider: "campspot",
    slug: "amazing-rocky-park-campground",
    name: "Amazing Rocky Park - Daiva RV Resorts, Durham",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/amazing-rocky-park-campground",
  },
  {
    provider: "campspot",
    slug: "bear-lake-experience-warwick",
    name: "Bear Lake Experience, Warwick",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/bear-lake-experience-warwick",
  },
  {
    provider: "campspot",
    slug: "beausoleil-first-nation",
    name: "Beausoleil First Nation, Christian Island",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/beausoleil-first-nation",
  },
  {
    provider: "campspot",
    slug: "revive-beeline",
    name: "Bee Line Park, Aylmer",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/revive-beeline",
  },
  {
    provider: "campspot",
    slug: "bloom-resorts-arran-lake",
    name: "Bloom Resorts Arran Lake",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/bloom-resorts-arran-lake",
  },
  {
    provider: "campspot",
    slug: "bloom-resorts-blue-mountains",
    name: "Bloom Resorts Blue Mountains",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/bloom-resorts-blue-mountains",
  },
  {
    provider: "campspot",
    slug: "bloom-resorts-cayuga",
    name: "Bloom Resorts Cayuga",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/bloom-resorts-cayuga",
  },
  {
    provider: "campspot",
    slug: "bloom-resorts-georgian-bay",
    name: "Bloom Resorts Georgian Bay",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/bloom-resorts-georgian-bay",
  },
  {
    provider: "campspot",
    slug: "bloom-resorts-hay-bay",
    name: "Bloom Resorts Hay Bay",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/bloom-resorts-hay-bay",
  },
  {
    provider: "campspot",
    slug: "bloom-resorts-huntsville",
    name: "Bloom Resorts Huntsville",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/bloom-resorts-huntsville",
  },
  {
    provider: "campspot",
    slug: "bloom-resorts-ipperwash",
    name: "Bloom Resorts Ipperwash",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/bloom-resorts-ipperwash",
  },
  {
    provider: "campspot",
    slug: "bloom-resorts-penetanguishene",
    name: "Bloom Resorts Penetanguishene",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/bloom-resorts-penetanguishene",
  },
  {
    provider: "campspot",
    slug: "bloom-resorts-sandbanks",
    name: "Bloom Resorts Sandbanks",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/bloom-resorts-sandbanks",
  },
  {
    provider: "campspot",
    slug: "bloom-resorts-stratford",
    name: "Bloom Resorts Stratford",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/bloom-resorts-stratford",
  },
  {
    provider: "campspot",
    slug: "bloom-resorts-turkey-point",
    name: "Bloom Resorts Turkey Point",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/bloom-resorts-turkey-point",
  },
  {
    provider: "campspot",
    slug: "bobcaygeon-shores-cottage-resort",
    name: "Bobcaygeon Shores Cottage Resort, Bobcaygeon",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/bobcaygeon-shores-cottage-resort",
  },
  {
    provider: "campspot",
    slug: "bruceslanding",
    name: "Bruce's Landing RV Resort",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/bruceslanding",
  },
  {
    provider: "campspot",
    slug: "cameronspoint",
    name: "Cameron's Point Family Campground",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/cameronspoint",
  },
  {
    provider: "campspot",
    slug: "camp-hillbilly",
    name: "Camp Hillbilly - Daiva RV Resorts, Gravenhurst",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/camp-hillbilly",
  },
  {
    provider: "campspot",
    slug: "capecrokerpark",
    name: "Cape Croker Park",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/capecrokerpark",
  },
  {
    provider: "campspot",
    slug: "cedarvalleylindsay",
    name: "Cedar Valley Cottage Resort",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/cedarvalleylindsay",
  },
  {
    provider: "campspot",
    slug: "ingersoll-camping",
    name: "Centennial Park Camping, Ingersoll",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/ingersoll-camping",
  },
  {
    provider: "campspot",
    slug: "cosmocamping",
    name: "Cosmo Camping, Lansdowne",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/cosmocamping",
  },
  {
    provider: "campspot",
    slug: "crystal-beach",
    name: "Crystal Beach - Daiva RV Resorts, Ridgeway",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/crystal-beach",
  },
  {
    provider: "campspot",
    slug: "driftwood-beach-resort",
    name: "Driftwood Beach Resort",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/driftwood-beach-resort",
  },
  {
    provider: "campspot",
    slug: "duck-lake-rv-resort",
    name: "Duck Lake RV Resort",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/duck-lake-rv-resort",
  },
  {
    provider: "campspot",
    slug: "duttonapark",
    name: "Duttona Family Campground",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/duttonapark",
  },
  {
    provider: "campspot",
    slug: "gateway-camping",
    name: "Gateway Camping - Daiva RV Resorts, Wasaga Beach",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/gateway-camping",
  },
  {
    provider: "campspot",
    slug: "glenhavenresort",
    name: "Glen Haven Resort, Arden",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/glenhavenresort",
  },
  {
    provider: "campspot",
    slug: "grand-valley",
    name: "Grand Valley - Daiva RV Resorts, Grand Valley",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/grand-valley",
  },
  {
    provider: "campspot",
    slug: "great-canadian-campground",
    name: "Great Canadian Resorts and Campgrounds, Marmora",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/great-canadian-campground",
  },
  {
    provider: "campspot",
    slug: "hammockharbourrvpark",
    name: "Hammock Harbour RV Park",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/hammockharbourrvpark",
  },
  {
    provider: "campspot",
    slug: "hammondhill",
    name: "Hammond Hill",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/hammondhill",
  },
  {
    provider: "campspot",
    slug: "highfallsbay",
    name: "High Falls Bay Cottages, Camping & Waterpark",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/highfallsbay",
  },
  {
    provider: "campspot",
    slug: "holiday-park-wasaga-on",
    name: "Holiday Park- Daiva RV Resorts, Wasaga",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/holiday-park-wasaga-on",
  },
  {
    provider: "campspot",
    slug: "huntsville-lagoons",
    name: "Huntsville Lagoons - Daiva RV Resorts, Huntsville",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/huntsville-lagoons",
  },
  {
    provider: "campspot",
    slug: "revive-kenorus",
    name: "Kenorus Campground - Port Elgin, ON",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/revive-kenorus",
  },
  {
    provider: "campspot",
    slug: "kittawa",
    name: "Kittawa RV Resort, Limoges",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/kittawa",
  },
  {
    provider: "campspot",
    slug: "lakesidevillagepark",
    name: "Lakeside Village Park, Wheatley",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/lakesidevillagepark",
  },
  {
    provider: "campspot",
    slug: "magnetawanriverresort",
    name: "Magnetawan River Resort",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/magnetawanriverresort",
  },
  {
    provider: "campspot",
    slug: "maidenbaycamp",
    name: "Maiden Bay Camp, North Cobalt",
    region: "Northeastern",
    vendorUrl: "https://www.campspot.com/book/maidenbaycamp",
  },
  {
    provider: "campspot",
    slug: "maitland-shores-resort",
    name: "Maitland Shores Resort, Dunnville",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/maitland-shores-resort",
  },
  {
    provider: "campspot",
    slug: "maplegrove-christianretreat",
    name: "Maple Grove Christian Retreat Centre, Thamesford",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/maplegrove-christianretreat",
  },
  {
    provider: "campspot",
    slug: "maplesrvpark",
    name: "Maples RV Park",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/maplesrvpark",
  },
  {
    provider: "campspot",
    slug: "noelvillefamilyresort",
    name: "Noelville Family Resort, Noelville",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/noelvillefamilyresort",
  },
  {
    provider: "campspot",
    slug: "oreilly-lake-resort",
    name: "O'Reilly Lake Resort, Mountain Grove",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/oreilly-lake-resort",
  },
  {
    provider: "campspot",
    slug: "ottawa-east",
    name: "Ottawa East - Daiva RV Resorts, Alfred",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/ottawa-east",
  },
  {
    provider: "campspot",
    slug: "pine-ridge-park",
    name: "Pine Ridge Park, Petawawa",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/pine-ridge-park",
  },
  {
    provider: "campspot",
    slug: "pleasant-beach",
    name: "PLB Pleasant Beach Campground",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/pleasant-beach",
  },
  {
    provider: "campspot",
    slug: "reid-lake",
    name: "Reid Lake - Daiva RV Resorts, Renfrew",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/reid-lake",
  },
  {
    provider: "campspot",
    slug: "river-little",
    name: "River Little, Bracebridge",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/river-little",
  },
  {
    provider: "campspot",
    slug: "rochesterplace",
    name: "Rochester Place Resort",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/rochesterplace",
  },
  {
    provider: "campspot",
    slug: "roebuck-family-campground",
    name: "Roebuck - Daiva RV Resorts, Meaford",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/roebuck-family-campground",
  },
  {
    provider: "campspot",
    slug: "sand-hill-park",
    name: "Sand Hill Park, Port Burwell",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/sand-hill-park",
  },
  {
    provider: "campspot",
    slug: "sandbanks-river-country-campground",
    name: "Sandbanks River Country Campground, Cherry Valley",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/sandbanks-river-country-campground",
  },
  {
    provider: "campspot",
    slug: "serpent-river",
    name: "Serpent River Campground",
    region: "Northeastern",
    vendorUrl: "https://www.campspot.com/book/serpent-river",
  },
  {
    provider: "campspot",
    slug: "sun-retreats-sherkston-shores",
    name: "SKS Sun Retreats Sherkston Shores",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/sun-retreats-sherkston-shores",
  },
  {
    provider: "campspot",
    slug: "sleepy-cedars-family-camping",
    name: "Sleepy Cedars Family Camping",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/sleepy-cedars-family-camping",
  },
  {
    provider: "campspot",
    slug: "south-algonquin",
    name: "South Algonquin - Daiva RV Resorts, Harcourt",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/south-algonquin",
  },
  {
    provider: "campspot",
    slug: "splashvalley",
    name: "Splash Valley Waterpark and Resort - Cobden, ON",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/splashvalley",
  },
  {
    provider: "campspot",
    slug: "steamboatbayrvresort",
    name: "Steamboat Bay RV Resort, Haley Station",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/steamboatbayrvresort",
  },
  {
    provider: "campspot",
    slug: "stoney-lake",
    name: "Stoney Lake - Daiva RV Resorts, Lakefield",
    region: "Central Ontario",
    vendorUrl: "https://www.campspot.com/book/stoney-lake",
  },
  {
    provider: "campspot",
    slug: "twinlakescamping",
    name: "Twin Lakes Camping",
    region: "Northeastern",
    vendorUrl: "https://www.campspot.com/book/twinlakescamping",
  },
  {
    provider: "campspot",
    slug: "uppercanadacampground",
    name: "Upper Canada Campground",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/uppercanadacampground",
  },
  {
    provider: "campspot",
    slug: "waterways",
    name: "Waterways RV Resort",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/waterways",
  },
  {
    provider: "campspot",
    slug: "whitewatercottageandrv",
    name: "Whitewater Cottage & RV Resort",
    region: "Eastern Ontario",
    vendorUrl: "https://www.campspot.com/book/whitewatercottageandrv",
  },
  {
    provider: "campspot",
    slug: "willowood-on",
    name: "Willowood Resort",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/willowood-on",
  },
  {
    provider: "campspot",
    slug: "jellystone-niagara-ca",
    name: "Yogi Bear's Jellystone Park\u2122 Camp-Resort: Niagara Falls",
    region: "Southwestern Ontario",
    vendorUrl: "https://www.campspot.com/book/jellystone-niagara-ca",
  },
];

const CAMPSPOT_ONTARIO_BOOKABLE_PARK_SLUGS = new Set([
  "algonquin-pines",
  "bear-lake-experience-warwick",
  "beausoleil-first-nation",
  "revive-beeline",
  "bobcaygeon-shores-cottage-resort",
  "bruceslanding",
  "cedarvalleylindsay",
  "driftwood-beach-resort",
  "duck-lake-rv-resort",
  "duttonapark",
  "glenhavenresort",
  "great-canadian-campground",
  "hammockharbourrvpark",
  "hammondhill",
  "ingersoll-camping",
  "revive-kenorus",
  "kittawa",
  "magnetawanriverresort",
  "maidenbaycamp",
  "maitland-shores-resort",
  "maplegrove-christianretreat",
  "maplesrvpark",
  "noelvillefamilyresort",
  "oreilly-lake-resort",
  "river-little",
  "rochesterplace",
  "sand-hill-park",
  "sandbanks-river-country-campground",
  "serpent-river",
  "sun-retreats-sherkston-shores",
  "splashvalley",
  "twinlakescamping",
  "waterways",
  "whitewatercottageandrv",
]);

const CAMPSPOT_ONTARIO_BOOKABLE_PARKS = CAMPSPOT_ONTARIO_PRIVATE_PARKS
  .filter((park) => CAMPSPOT_ONTARIO_BOOKABLE_PARK_SLUGS.has(park.slug));

export const OPERATORS: OperatorConfig[] = [
  ONTARIO_PARKS,
  PARKS_CANADA,
  ST_LAWRENCE_PARKS,
  gtc("lprca",        "Long Point Region CA",   "longpoint.goingtocamp.com"),
  gtc("stclair",      "St. Clair Region CA",    "stclair.goingtocamp.com"),
  gtc("otonabee",     "Otonabee Region CA",     "otonabee.goingtocamp.com"),
  gtc("npca",         "Niagara Peninsula CA",   "niagara.goingtocamp.com"),
  gtc("trca",         "Toronto and Region CA",  "camping.trca.ca"),
  gtc("grca",         "Grand River CA",         "www.grcacamping.ca"),
  gtc("upperthames",  "Upper Thames River CA",  "upperthames.goingtocamp.com"),
  gtc("maitland",     "Maitland Valley CA",     "maitlandvalley.goingtocamp.com"),
  gtc("catfish",      "Catfish Creek CA",       "catfishcreek.goingtocamp.com"),
  gtc("hca",          "Hamilton Conservation Authority", "hcareservations.ca"),
  {
    id: "campspot_saugeen",
    name: "Saugeen Valley Conservation Authority",
    vendor: "campspot",
    base_url: "https://www.campspot.com",
    booking_url: "https://www.campspot.com/book",
    active: true,
    providerParks: [
      {
        provider: "campspot",
        slug: "durham",
        name: "Durham Conservation Area",
        region: "Southwestern Ontario",
        vendorUrl: "https://www.campspot.com/book/durham",
      },
      {
        provider: "campspot",
        slug: "saugeenbluffs",
        name: "Saugeen Bluffs Conservation Area",
        region: "Southwestern Ontario",
        vendorUrl: "https://www.campspot.com/book/saugeenbluffs",
      },
    ],
  },
  {
    id: "campspot_rrca",
    name: "Raisin Region Conservation Authority",
    vendor: "campspot",
    base_url: "https://www.campspot.com",
    booking_url: "https://www.campspot.com/book",
    active: true,
    providerParks: [
      {
        provider: "campspot",
        slug: "charlottenburghpark",
        name: "Charlottenburgh Park",
        region: "Eastern Ontario",
        vendorUrl: "https://www.campspot.com/book/charlottenburghpark",
      },
    ],
  },
  {
    id: "campspot_ontario_private",
    name: "Campspot Ontario Campgrounds",
    vendor: "campspot",
    base_url: "https://www.campspot.com",
    booking_url: "https://www.campspot.com/book",
    active: true,
    providerParks: CAMPSPOT_ONTARIO_BOOKABLE_PARKS,
  },
  {
    id: "letscamp_quinte",
    name: "Quinte Conservation",
    vendor: "letscamp",
    base_url: "https://letscamp.ca",
    booking_url: "https://letscamp.ca/camps",
    active: true,
    providerParks: [
      {
        provider: "letscamp",
        slug: "depot-lakes",
        name: "Depot Lakes Conservation Area",
        region: "Eastern Ontario",
        vendorUrl: "https://letscamp.ca/camps/depot-lakes",
      },
    ],
  },
  {
    id: "letscamp_lowerthames",
    name: "Lower Thames Valley Conservation Authority",
    vendor: "letscamp",
    base_url: "https://letscamp.ca",
    booking_url: "https://letscamp.ca/camps",
    active: true,
    providerParks: [
      {
        provider: "letscamp",
        slug: "big-bend",
        name: "Big Bend Conservation Area",
        region: "Southwestern Ontario",
        vendorUrl: "https://letscamp.ca/camps/big-bend",
      },
      {
        provider: "letscamp",
        slug: "cm-wilson",
        name: "C.M. Wilson Conservation Area",
        region: "Southwestern Ontario",
        vendorUrl: "https://letscamp.ca/camps/cm-wilson",
      },
    ],
  },
];
